package com.wookidoki.profitlogic.service;

import com.wookidoki.profitlogic.common.exception.ResourceNotFoundException;
import com.wookidoki.profitlogic.domain.*;
import com.wookidoki.profitlogic.dto.mypage.*;
import com.wookidoki.profitlogic.repository.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class MyPageService {

    private final UserRepository userRepository;
    private final ProjectRepository projectRepository;
    private final ChatLogRepository chatLogRepository;
    private final BoardPostRepository boardPostRepository;
    private final CommentRepository commentRepository;
    private final CostDetailRepository costDetailRepository;
    private final TimeLogRepository timeLogRepository;
    private final DailyLogRepository dailyLogRepository;

    @Transactional(readOnly = true)
    public UserProfileResponse getProfile(Long userId) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("사용자", userId));

        int projectCount = projectRepository.findByUserId(userId).size();
        long chatCount = chatLogRepository.countByUserId(userId);
        long postCount = boardPostRepository.findByUserId(userId).size();

        return UserProfileResponse.builder()
                .id(user.getId())
                .email(user.getEmail())
                .nickname(user.getNickname())
                .bizType(user.getBizType() != null ? user.getBizType().name() : null)
                .role(user.getRole().name())
                .createdAt(user.getCreatedAt())
                .projectCount(projectCount)
                .totalChatCount(chatCount)
                .totalPostCount(postCount)
                .build();
    }

    @Transactional
    public DailyLogResponse getDailyLog(Long userId, LocalDate date) {
        return dailyLogRepository.findByUserIdAndLogDate(userId, date)
                .map(this::toResponse)
                .orElseGet(() -> toResponse(autoGenerate(userId, date)));
    }

    @Transactional(readOnly = true)
    public List<DailyLogResponse> getDailyLogs(Long userId, LocalDate start, LocalDate end) {
        return dailyLogRepository
                .findByUserIdAndLogDateBetweenOrderByLogDateDesc(userId, start, end)
                .stream()
                .map(this::toResponse)
                .toList();
    }

    @Transactional
    public DailyLogResponse updateMemo(Long userId, LocalDate date, String memo) {
        DailyLog dailyLog = dailyLogRepository.findByUserIdAndLogDate(userId, date)
                .orElseGet(() -> autoGenerate(userId, date));
        dailyLog.updateMemo(memo);
        return toResponse(dailyLogRepository.save(dailyLog));
    }

    // ── Auto-generation ──

    private DailyLog autoGenerate(Long userId, LocalDate date) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("사용자", userId));

        LocalDateTime dayStart = date.atStartOfDay();
        LocalDateTime dayEnd = date.atTime(LocalTime.MAX);

        String projectSummary = buildProjectSummary(userId, dayStart, dayEnd);
        String costSummary = buildCostSummary(userId, dayStart, dayEnd);
        String timeLogSummary = buildTimeLogSummary(userId, date);
        String chatSummary = buildChatSummary(userId, dayStart, dayEnd);
        String communitySummary = buildCommunitySummary(userId, dayStart, dayEnd);

        DailyLog dailyLog = DailyLog.builder()
                .user(user)
                .logDate(date)
                .projectSummary(projectSummary)
                .costSummary(costSummary)
                .timeLogSummary(timeLogSummary)
                .chatSummary(chatSummary)
                .communitySummary(communitySummary)
                .autoGenerated(true)
                .build();

        log.info("일일 기록 자동 생성 - userId: {}, date: {}", userId, date);
        return dailyLogRepository.save(dailyLog);
    }

    private String buildProjectSummary(Long userId, LocalDateTime start, LocalDateTime end) {
        List<Project> projects = projectRepository.findByUserId(userId).stream()
                .filter(p -> !p.getCreatedAt().isBefore(start) && !p.getCreatedAt().isAfter(end))
                .toList();
        if (projects.isEmpty()) return null;

        StringBuilder sb = new StringBuilder();
        for (Project p : projects) {
            sb.append("- ").append(p.getTitle()).append(" (신규 생성)\n");
        }
        return sb.toString().trim();
    }

    private String buildCostSummary(Long userId, LocalDateTime start, LocalDateTime end) {
        List<CostDetail> costs = costDetailRepository.findByUserIdAndCreatedAtBetween(userId, start, end);
        if (costs.isEmpty()) return null;

        StringBuilder sb = new StringBuilder();
        for (CostDetail c : costs) {
            sb.append("- ").append(c.getCostName())
                    .append(": ").append(String.format("%,d", c.getAmount().longValue())).append("원")
                    .append(" (").append(c.getCategory().name()).append(")\n");
        }
        return sb.toString().trim();
    }

    private String buildTimeLogSummary(Long userId, LocalDate date) {
        List<TimeLog> timeLogs = timeLogRepository.findByUserIdAndLogDate(userId, date);
        if (timeLogs.isEmpty()) return null;

        StringBuilder sb = new StringBuilder();
        for (TimeLog t : timeLogs) {
            sb.append("- ").append(t.getTaskName())
                    .append(": ").append(t.getHoursSpent()).append("시간\n");
        }
        return sb.toString().trim();
    }

    private String buildChatSummary(Long userId, LocalDateTime start, LocalDateTime end) {
        List<ChatLog> chats = chatLogRepository.findByUserIdAndCreatedAtBetween(userId, start, end);
        if (chats.isEmpty()) return null;

        StringBuilder sb = new StringBuilder();
        sb.append(chats.size()).append("건의 AI 상담\n");
        for (ChatLog c : chats) {
            String q = c.getQuestion().length() > 50
                    ? c.getQuestion().substring(0, 50) + "..."
                    : c.getQuestion();
            sb.append("- \"").append(q).append("\"\n");
        }
        return sb.toString().trim();
    }

    private String buildCommunitySummary(Long userId, LocalDateTime start, LocalDateTime end) {
        List<BoardPost> posts = boardPostRepository.findByUserIdAndCreatedAtBetween(userId, start, end);
        List<Comment> comments = commentRepository.findByUserIdAndCreatedAtBetween(userId, start, end);
        if (posts.isEmpty() && comments.isEmpty()) return null;

        StringBuilder sb = new StringBuilder();
        if (!posts.isEmpty()) {
            sb.append("게시글 ").append(posts.size()).append("건 작성\n");
            for (BoardPost p : posts) {
                sb.append("- \"").append(p.getTitle()).append("\"\n");
            }
        }
        if (!comments.isEmpty()) {
            sb.append("댓글 ").append(comments.size()).append("건 작성\n");
        }
        return sb.toString().trim();
    }

    private DailyLogResponse toResponse(DailyLog log) {
        return DailyLogResponse.builder()
                .id(log.getId())
                .logDate(log.getLogDate())
                .projectSummary(log.getProjectSummary())
                .costSummary(log.getCostSummary())
                .timeLogSummary(log.getTimeLogSummary())
                .chatSummary(log.getChatSummary())
                .communitySummary(log.getCommunitySummary())
                .personalMemo(log.getPersonalMemo())
                .autoGenerated(log.getAutoGenerated())
                .createdAt(log.getCreatedAt())
                .updatedAt(log.getUpdatedAt())
                .build();
    }
}
