package com.wookidoki.profitlogic.dto.mypage;

import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Getter
@AllArgsConstructor
@Builder
public class DailyLogResponse {
    private Long id;
    private LocalDate logDate;
    private String projectSummary;
    private String costSummary;
    private String timeLogSummary;
    private String chatSummary;
    private String communitySummary;
    private String personalMemo;
    private boolean autoGenerated;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
