package com.wookidoki.profitlogic.domain;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

@Entity
@Table(name = "daily_logs", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"user_id", "log_date"})
})
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@Builder
public class DailyLog extends BaseTimeEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @Column(name = "log_date", nullable = false)
    private LocalDate logDate;

    @Lob
    @Column(name = "project_summary", columnDefinition = "TEXT")
    private String projectSummary;

    @Lob
    @Column(name = "cost_summary", columnDefinition = "TEXT")
    private String costSummary;

    @Lob
    @Column(name = "time_log_summary", columnDefinition = "TEXT")
    private String timeLogSummary;

    @Lob
    @Column(name = "chat_summary", columnDefinition = "TEXT")
    private String chatSummary;

    @Lob
    @Column(name = "community_summary", columnDefinition = "TEXT")
    private String communitySummary;

    @Lob
    @Column(name = "personal_memo", columnDefinition = "TEXT")
    private String personalMemo;

    @Column(name = "auto_generated", nullable = false)
    @Builder.Default
    private Boolean autoGenerated = false;

    public void updateMemo(String personalMemo) {
        this.personalMemo = personalMemo;
    }
}
